backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "public/content/data.json"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Hero Sectie"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Subtitel", name: "subtitle", widget: "text"}
              - {label: "Achtergrond Afbeelding", name: "image", widget: "image"}

          - label: "Ons Ambacht Sectie"
            name: "craft"
            widget: "object"
            fields:
              - {label: "Afbeelding", name: "image", widget: "image"}

          - label: "Pizza Menu"
            name: "menu"
            widget: "list"
            summary: '{{fields.name}}'
            fields:
              - {label: "Naam", name: "name", widget: "string"}
              - {label: "Beschrijving", name: "desc", widget: "text"}
              - {label: "Prijs (optioneel)", name: "price", widget: "string", required: false}

          - label: "Live Cooking Media"
            name: "media"
            widget: "list"
            fields:
              - {label: "Omslagafbeelding", name: "image", widget: "image"}
              - {label: "Video Link (optioneel)", name: "videoUrl", widget: "string", required: false}