backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "public/content/data.json"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Subtitle", name: "heroSubtitle", widget: "text"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}